[versions]
agp = "8.12.3"
apimanager = "2.2.4"
dokka = "2.1.0"
equinox-backend = "1.1.6"
equinox = "1.1.7"
# backend
kassaforte = "1.0.0beta-01"
kotlinxCoroutinesCore = "1.10.2"
spring = "3.2.3"
jacksonDatabind = "2.15.4"
jsch = "2.27.4"
json = "20250517"
mysqlConnectorJava = "8.0.33"
# core
kotlinxSerializationJson = "1.9.0"

[libraries]
dokka-base = { module = "org.jetbrains.dokka:dokka-base", version.ref = "dokka" }
equinox-backend = { module = "io.github.n7ghtm4r3:equinox-backend", version.ref = "equinox-backend" }
equinox-core = { module = "io.github.n7ghtm4r3:equinox-core", version.ref = "equinox" }
# backend
apimanager = { module = "com.github.N7ghtm4r3:APIManager", version.ref = "apimanager" }
jsch = { module = "com.github.mwiede:jsch", version.ref = "jsch" }
json = { module = "org.json:json", version.ref = "json" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring" }
mysql-connector-java = { module = "mysql:mysql-connector-java", version.ref = "mysqlConnectorJava" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jacksonDatabind" }
kassaforte = { module = "io.github.n7ghtm4r3:kassaforte", version.ref = "kassaforte" }
# core
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

